[workspace]
members = [
    "objc2",
    "objc-sys",
    "objc2-encode",
    "objc2-foundation",
    "objc2-proc-macros",
    "block2",
    "block-sys",
    "tests",
    "test-assembly",
    "test-assembly/crates/*",
    "test-ui",
]
resolver = "2"

[profile.assembly-tests]
inherits = "release"
# Enable LTO to allow testing the `unstable-static-sel-inlined` feature
lto = true
