[package]
name = "icrate"
version = "0.0.1"
authors = ["Mads Marquart <mads@marquart.dk>"]
edition = "2021"
rust-version = "1.60"

description = "Bindings to Apple's frameworks"
keywords = ["macos", "ios", "cocoa", "apple", "framework"]
categories = [
    "accessibility",
    "api-bindings",
    "development-tools::ffi",
    "external-ffi-bindings",
    "os::macos-apis",
]
readme = "README.md"
repository = "https://github.com/madsmtm/objc2"
documentation = "https://docs.rs/icrate/"
license = "MIT"

[dependencies]
objc2 = { path = "../objc2", version = "=0.3.0-beta.4", default-features = false, optional = true }
block2 = { path = "../block2", version = "=0.2.0-alpha.7", default-features = false, optional = true }

# Provide methods to convert between `uuid::Uuid` and `icrate::Foundation::NSUUID`
uuid = { version = "1.1.2", optional = true, default-features = false }

[package.metadata.docs.rs]
default-target = "x86_64-apple-darwin"
features = ["block", "objective-c", "uuid", "unstable-frameworks-all", "unstable-docsrs"]

targets = [
    # MacOS
    "x86_64-apple-darwin",
    "aarch64-apple-darwin",
    # "i686-apple-darwin",
    # iOS
    "aarch64-apple-ios",
    "x86_64-apple-ios",
    # "armv7-apple-ios",
    # "i386-apple-ios",
    # GNUStep
    "x86_64-unknown-linux-gnu",
    "i686-unknown-linux-gnu",
    # Windows
    "x86_64-pc-windows-msvc",
]

[[example]]
name = "basic_usage"
required-features = ["Foundation"]

[[example]]
name = "delegate"
required-features = ["apple", "Foundation"]

[[example]]
name = "speech_synthesis"
required-features = ["apple", "Foundation"]

[[example]]
name = "nspasteboard"
required-features = ["apple", "Foundation"]

[features]
default = ["std", "apple"]

# Currently not possible to turn off, put here for forwards compatibility.
std = ["alloc", "objc2?/std", "block2?/std"]
alloc = ["objc2?/alloc", "block2?/alloc"]

# Runtime selection. See `objc-sys` for details.
apple = ["objc2?/apple", "block2?/apple"]
gnustep-1-7 = ["objc2?/gnustep-1-7", "block2?/gnustep-1-7"]
gnustep-1-8 = ["gnustep-1-7", "objc2?/gnustep-1-8", "block2?/gnustep-1-8"]
gnustep-1-9 = ["gnustep-1-8", "objc2?/gnustep-1-9", "block2?/gnustep-1-9"]
gnustep-2-0 = ["gnustep-1-9", "objc2?/gnustep-2-0", "block2?/gnustep-2-0"]
gnustep-2-1 = ["gnustep-2-0", "objc2?/gnustep-2-1", "block2?/gnustep-2-1"]

# Expose features that requires Objective-C.
objective-c = ["objc2"]

# Expose features that requires creating blocks.
block = ["objc2?/block", "block2"]

# For better documentation on docs.rs
unstable-docsrs = []

# Frameworks

AppKit = ["Foundation", "CoreData"]
AuthenticationServices = ["Foundation"]
CoreData = ["Foundation"]
Foundation = ["objective-c", "block"]

# Helps with CI
unstable-frameworks-all = ["AppKit", "AuthenticationServices", "CoreData", "Foundation"]
unstable-frameworks-gnustep = ["AppKit", "Foundation"]
unstable-frameworks-gnustep-32bit = ["Foundation"]
unstable-frameworks-ios = ["AuthenticationServices", "CoreData", "Foundation"]
unstable-frameworks-macos-10-7 = ["AppKit", "CoreData", "Foundation"]
unstable-frameworks-macos-10-13 = ["unstable-frameworks-macos-10-7"]
unstable-frameworks-macos-11 = ["unstable-frameworks-macos-10-13", "AuthenticationServices"]
unstable-frameworks-macos-12 = ["unstable-frameworks-macos-11"]
