[package]
name = "test-assembly"
version = "0.1.0"
edition = "2021"
publish = false

repository = "https://github.com/madsmtm/objc2"
license = "MIT"

build = "build.rs"

[dependencies]
cargo_metadata = "0.14"
